openapi: 3.0.0
info:
  title: DeployBoard
  version: '1.0'
  description: DeployBoard API
  contact:
    email: support@deployboard.io
servers:
  - url: 'https://dev-api.deployboard.io'
    description: dev
  - url: 'https://api.deployboard.io'
    description: prod
  - url: 'http://localhost:3000'
    description: local
paths:
  /put:
    get:
      summary: /put GET
      tags: []
      responses: {}
      parameters:
        - schema:
            type: string
          in: query
          name: app
          required: true
          description: Application Name
        - schema:
            type: string
          in: query
          name: env
          required: true
          description: |
            Environment
        - schema:
            type: string
          in: query
          name: version
          required: true
          description: Version
        - schema:
            type: string
            enum:
              - Deploying
              - Deployed
          in: query
          name: status
          required: true
          description: Status
        - schema:
            type: string
          in: header
          name: X-API-Key
          required: true
      description: ''
    post:
      summary: /put POST
      responses:
        '200':
          description: '{"message": "ok"}'
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app:
                  type: string
                env:
                  type: string
                version:
                  type: string
                status:
                  type: string
              required:
                - app
                - env
                - version
                - status
            examples:
              Example:
                value:
                  app: UI
                  env: Dev
                  version: 1.0.0
                  status: Deployed
  /get:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          required: true
  /get/apikeys:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
  /get/logs:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          required: true
        - schema:
            type: string
          in: query
          name: app
          description: Application Name
          required: true
        - schema:
            type: string
          in: query
          name: env
          description: Environment
          required: true
    parameters: []
  /getu:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      description: ''
components:
  schemas: {}
  securitySchemes: {}
